### ISSUE TITLE
请问这个能本地测试吗

### ISSUE THREAD

**Issue by wonderffee** [goodow/GDOperation#14]
看到你提供了web端的代码，测试可以运行，就是这个iOS端怎么与这个web端对接起来，找了没有url地址，难道是只用firebase的，不能用局域网？

**Comment by larrytin** [comment]
网络接口使用的是 [GDChannel](https://github.com/goodow/GDChannel) 这个库, 有多个实现, 包括 MQTT 和 Firebase, GDOperation 默认使用 Firebase, 这样无需自已搭建后台服务. 也可以很方便的切换到其它实现上去.

**Comment by larrytin** [comment]
以前也自己实现过服务端部分, 后台代码见 [realtime-store](https://github.com/goodow/realtime-store)

**Comment by wonderffee** [comment]
所以Firebase 的配置是在GoogleService-Info.plist 这个文件中对吧？
以前没有用过firebase，但是知道这个东西，也有点感兴趣，如果我要启用本地测试，即web端是本地的用局域网网址192.168.0.xx的网址进行访问，那么我的firebase要与这个iOS客户端对接，除了修改GoogleService-Info.plist 中的参数，还需要在firebase中进行配置对不，这个要怎么配置呢？

**Comment by larrytin** [comment]
微信语音?

**Comment by wonderffee** [comment]
@larrytin 已发邮件，微信吧
